#version: "3.9"

services:
  fhir-server:
    #image: costateixeira/hapistarter:2.0.0
   # image: jfcal/myhapi:latest
    image: hapiproject/hapi:latest
#    restart: unless-stopped
    restart: always
    container_name: ${server_name}
    ports:
      - 8080:8080
    logging:
      driver: "json-file"
      options: 
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
   # env_file:
   #   - .env

    environment:
      - server.servlet.context-path=/unicom
      - hapi.fhir.allow_multiple_delete=true
      - hapi.fhir.server_address=https://sandbox.hl7europe.eu/unicom/fhir
      - hapi.fhir.reuse_cached_search_results_millis=10000
      - hapi.fhir.cors.allow_Credentials=true
#      - hapi.fhir.cors.allowed_origin_patterns="*"
      - hapi.fhir.fhir_version=R5
      - hapi.fhir.cr_enabled=true


      - spring.main.allow-bean-definition-overriding=true
      - spring.jpa.properties.hibernate.format_sql=false
      - spring.jpa.properties.hibernate.show_sql=false
      - spring.jpa.properties.hibernate.dialect=ca.uhn.fhir.jpa.model.dialect.HapiFhirH2Dialect
      - spring.jpa.properties.hibernate.search.enabled=true
      - spring.jpa.properties.hibernate.search.backend.type=lucene
#      - spring.jpa.properties.hibernate.search.backend.analysis.configurer=ca.uhn.fhir.jpa.search.HapiHSearchAnalysisConfigurers$$HapiLuceneAnalysisConfigurer
      - spring.jpa.properties.hibernate.search.backend.directory.type=local-filesystem
      - spring.jpa.properties.hibernate.search.backend.directory.root=target/lucenefiles
      - spring.jpa.properties.hibernate.search.backend.lucene_version=lucene_current
      - spring.batch.job.enabled=false
      - hapi.fhir.openapi_enabled=true
      - hapi.fhir.use_apache_address_strategy_https=true
      - hapi.fhir.allow_contains_searches=true
      - hapi.fhir.allow_override_default_search_params=true
      - hapi.fhir.cql_enabled=true
      - hapi.fhir.advanced_lucene_indexing=false
      - hapi.fhir.bulk_export_enabled=false
      - hapi.fhir.bulk_import_enabled=false
      - hapi.fhir.graphql_enabled=true
      - hapi.fhir.mdm_enabled=false
      - hapi.fhir.cors.allowed_origin='*'
      - hapi.fhir.ig_runtime_upload_enabled=true
      - hapi.fhir.custom_content_path=/custom
      - hapi.fhir.app_content_path=/apps
      - hapi.fhir.tester.home.name="Local Tester"
      - hapi.fhir.tester.home.server_address=https://sandbox.hl7europe.eu/unicom/fhir
      - hapi.fhir.tester.home.fhir_version=R5

    volumes:
#      - ./default:/static
      - ./web:/custom
      - ./apps:/apps
