@host = http://localhost:8080/fhir



### Post fixed StructureMap which is not integrated in the implementation guide 
GET {{host}}/metadata


### Post fixed StructureMap which is not integrated in the implementation guide 
POST {{host}}/InventoryItem HTTP/1.1
Accept: application/fhir+json;fhirVersion=5.0
Content-Type: application/fhir+json;fhirVersion=5.0

{
  "resourceType" : "InventoryItem",
  "id" : "example",
  "text" : {
    "status" : "generated",
    "div" : "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p><b>Generated Narrative: InventoryItem</b><a name=\"example\"> </a></p><div style=\"display: inline-block; background-color: #d9e0e7; padding: 6px; margin: 4px; border: 1px solid #8da1b4; border-radius: 5px; line-height: 60%\"><p style=\"margin-bottom: 0px\">Resource InventoryItem &quot;example&quot; </p></div><p><b>status</b>: active</p></div>"
  },
  "status" : "active"
}